// Code generated by modgen (make setup). DO NOT EDIT.

package main

import (
	"github.com/google/wire"

	"codebasego/internal/common"
	"codebasego/internal/modules/auth"
	"codebasego/internal/modules/graphql"
	"codebasego/internal/modules/health"
	"codebasego/internal/modules/page"
	"codebasego/internal/modules/seo"
	"codebasego/internal/modules/setting"
	"codebasego/internal/modules/user"
)

// EnabledModulesSet aggregates Wire provider sets for all active modules.
var EnabledModulesSet = wire.NewSet(
	auth.ProviderSet,
	graphql.ProviderSet,
	health.ProviderSet,
	page.ProviderSet,
	seo.ProviderSet,
	setting.ProviderSet,
	user.ProviderSet,
	wire.Bind(new(auth.UserService), new(*user.Service)),
	wire.Bind(new(graphql.UserService), new(*user.Service)),
	wire.Bind(new(graphql.AuthService), new(*auth.Service)),
)

// ProvideMigrators aggregates database auto-migrators for active modules.
func ProvideMigrators(
	authMod *auth.Module,
	pageMod *page.Module,
	seoMod *seo.Module,
	settingMod *setting.Module,
	userMod *user.Module,
) []common.Migrator {
	return []common.Migrator{
		authMod,
		pageMod,
		seoMod,
		settingMod,
		userMod,
	}
}

// ProvideRouteRegistrars aggregates route registrars for active modules.
func ProvideRouteRegistrars(
	authMod *auth.Module,
	graphqlMod *graphql.Module,
	healthMod *health.Module,
	pageMod *page.Module,
	seoMod *seo.Module,
	settingMod *setting.Module,
	userMod *user.Module,
) []common.RouteRegistrar {
	return []common.RouteRegistrar{
		authMod,
		graphqlMod,
		healthMod,
		pageMod,
		seoMod,
		settingMod,
		userMod,
	}
}

// ProvideBackgroundWorkers aggregates background workers for active modules.
func ProvideBackgroundWorkers(
	authMod *auth.Module,
) []common.BackgroundWorker {
	return []common.BackgroundWorker{
		authMod,
	}
}
