//go:build wireinject
// +build wireinject

package main

import (
	"github.com/google/wire"

	"codebasego/internal/platform/config"
	"codebasego/internal/platform/database"
	"codebasego/internal/platform/eventbus"
	"codebasego/internal/platform/logger"
	"codebasego/internal/platform/redis"
	"codebasego/internal/platform/server"
)

func InitializeApp() (*App, error) {
	wire.Build(
		// Platform infrastructure
		config.NewConfig,
		logger.NewLogger,
		database.NewDB,
		redis.NewClient,
		server.NewServer,
		eventbus.NewEventBus,
		eventbus.NewOutboxProcessor,

		// Active modules and DI aggregators (auto-generated by make setup from configs/modules.yaml)
		EnabledModulesSet,
		ProvideMigrators,
		ProvideRouteRegistrars,
		ProvideBackgroundWorkers,

		// App Root
		NewApp,
	)
	return nil, nil
}
