// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"codebasego/internal/modules/auth"
	"codebasego/internal/modules/graphql"
	"codebasego/internal/modules/health"
	"codebasego/internal/modules/page"
	"codebasego/internal/modules/seo"
	"codebasego/internal/modules/setting"
	"codebasego/internal/modules/user"
	"codebasego/internal/platform/config"
	"codebasego/internal/platform/database"
	"codebasego/internal/platform/eventbus"
	"codebasego/internal/platform/logger"
	"codebasego/internal/platform/redis"
	"codebasego/internal/platform/server"
)

import (
	_ "codebasego/docs"
)

// Injectors from wire.go:

func InitializeApp() (*App, error) {
	configConfig, err := config.NewConfig()
	if err != nil {
		return nil, err
	}
	db, err := database.NewDB(configConfig)
	if err != nil {
		return nil, err
	}
	zerologLogger := logger.NewLogger(configConfig)
	client, err := redis.NewClient(configConfig, zerologLogger)
	if err != nil {
		return nil, err
	}
	serverServer := server.NewServer(configConfig, zerologLogger, client)
	eventBus := eventbus.NewEventBus(configConfig, client, zerologLogger)
	outboxProcessor := eventbus.NewOutboxProcessor(db, eventBus, zerologLogger)
	gormRepository := user.NewGormRepository(db)
	service := user.NewService(gormRepository)
	gormRefreshTokenRepository := auth.NewGormRefreshTokenRepository(db)
	authService := auth.NewService(configConfig, service, gormRefreshTokenRepository, eventBus)
	handler := auth.NewHandler(authService)
	module := auth.NewModule(handler, authService)
	pageGormRepository := page.NewGormRepository(db)
	pageService := page.NewService(pageGormRepository)
	pageHandler := page.NewHandler(pageService)
	authMiddleware := auth.ProvideAuthMiddleware(module)
	pageModule := page.NewModule(pageHandler, authMiddleware)
	seoGormRepository := seo.NewGormRepository(db)
	seoService := seo.NewService(seoGormRepository)
	seoHandler := seo.NewHandler(seoService)
	seoModule := seo.NewModule(seoHandler, authMiddleware)
	settingGormRepository := setting.NewGormRepository(db)
	settingService := setting.NewService(settingGormRepository)
	settingHandler := setting.NewHandler(settingService)
	settingModule := setting.NewModule(settingHandler, authMiddleware)
	userHandler := user.NewHandler(service)
	userModule := user.NewModule(userHandler, authMiddleware)
	v := ProvideMigrators(module, pageModule, seoModule, settingModule, userModule)
	resolver := graphql.NewResolver(service, authService)
	graphqlModule := graphql.NewModule(resolver, configConfig, authService)
	healthHandler := health.NewHandler(db, client)
	healthModule := health.NewModule(healthHandler)
	v2 := ProvideRouteRegistrars(module, graphqlModule, healthModule, pageModule, seoModule, settingModule, userModule)
	v3 := ProvideBackgroundWorkers(module)
	app, err := NewApp(db, serverServer, outboxProcessor, v, v2, v3, eventBus)
	if err != nil {
		return nil, err
	}
	return app, nil
}
