package main

import (
	"bufio"
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"text/template"

	"gopkg.in/yaml.v3"
)

type ModuleEntry struct {
	Enabled     bool   `yaml:"enabled"`
	Description string `yaml:"description"`
}

type ModulesConfig struct {
	Modules map[string]ModuleEntry `yaml:"modules"`
}

type WireBind struct {
	Target       string
	Source       string
	SourceModule string
}

type ModuleInfo struct {
	Name           string
	ImportPath     string
	PackageName    string
	Enabled        bool
	Description    string
	HasProviderSet bool
	Binds          []WireBind
	HasAutoMigrate bool
	HasRoutes      bool
	HasBackground  bool
}

const modulesGenTemplate = `// Code generated by modgen (make setup). DO NOT EDIT.

package main

import (
	"github.com/google/wire"
{{- if not .HasAuthModule }}
	"github.com/gin-gonic/gin"
{{- end }}

	"codebasego/internal/common"
{{- range .ActiveModules }}
	"{{ .ImportPath }}"
{{- end }}
)

// EnabledModulesSet aggregates Wire provider sets for all active modules.
var EnabledModulesSet = wire.NewSet(
{{- range .ActiveModules }}
	{{ .PackageName }}.ProviderSet,
{{- end }}
{{- range .ActiveBinds }}
	wire.Bind(new({{ .Target }}), new({{ .Source }})),
{{- end }}
{{- if not .HasAuthModule }}
	ProvideFallbackAuthMiddleware,
{{- end }}
)

{{- if not .HasAuthModule }}
// ProvideFallbackAuthMiddleware provides a pass-through common.AuthMiddleware when the auth module is disabled.
func ProvideFallbackAuthMiddleware() common.AuthMiddleware {
	return common.AuthMiddleware(func(c *gin.Context) {
		c.Next()
	})
}
{{- end }}

// ProvideMigrators aggregates database auto-migrators for active modules.
func ProvideMigrators(
{{- range .MigratorModules }}
	{{ .PackageName }}Mod *{{ .PackageName }}.Module,
{{- end }}
) []common.Migrator {
	return []common.Migrator{
{{- range .MigratorModules }}
		{{ .PackageName }}Mod,
{{- end }}
	}
}

// ProvideRouteRegistrars aggregates route registrars for active modules.
func ProvideRouteRegistrars(
{{- range .RouteModules }}
	{{ .PackageName }}Mod *{{ .PackageName }}.Module,
{{- end }}
) []common.RouteRegistrar {
	return []common.RouteRegistrar{
{{- range .RouteModules }}
		{{ .PackageName }}Mod,
{{- end }}
	}
}

// ProvideBackgroundWorkers aggregates background workers for active modules.
func ProvideBackgroundWorkers(
{{- range .BackgroundModules }}
	{{ .PackageName }}Mod *{{ .PackageName }}.Module,
{{- end }}
) []common.BackgroundWorker {
	return []common.BackgroundWorker{
{{- range .BackgroundModules }}
		{{ .PackageName }}Mod,
{{- end }}
	}
}
`

var bindRegex = regexp.MustCompile(`@wire:bind\s+target=([^\s]+)\s+source=([^\s]+)`)

func main() {
	rootDir, err := findProjectRoot()
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error finding project root: %v\n", err)
		os.Exit(1)
	}

	modulesDir := filepath.Join(rootDir, "internal", "modules")
	configPath := filepath.Join(rootDir, "configs", "modules.yaml")
	genFile := filepath.Join(rootDir, "cmd", "api", "modules_gen.go")

	// 1. Load configs/modules.yaml
	cfg, err := loadModulesConfig(configPath)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error loading %s: %v\n", configPath, err)
		os.Exit(1)
	}

	// 2. Scan internal/modules/ for register.go
	discovered, err := scanModules(modulesDir)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error scanning modules directory: %v\n", err)
		os.Exit(1)
	}

	// 3. Sync discovered modules with configs/modules.yaml
	configChanged := false
	enabledMap := make(map[string]bool)
	discoveredMap := make(map[string]bool)
	for _, mod := range discovered {
		discoveredMap[mod.Name] = true
		if entry, exists := cfg.Modules[mod.Name]; exists {
			mod.Enabled = entry.Enabled
			if entry.Description != "" {
				mod.Description = entry.Description
			}
		} else {
			cfg.Modules[mod.Name] = ModuleEntry{
				Enabled:     true,
				Description: fmt.Sprintf("%s feature module", mod.Name),
			}
			mod.Enabled = true
			mod.Description = cfg.Modules[mod.Name].Description
			configChanged = true
		}
		enabledMap[mod.Name] = mod.Enabled
	}

	// Prune stale modules from config that are no longer on disk
	for modName := range cfg.Modules {
		if !discoveredMap[modName] {
			delete(cfg.Modules, modName)
			configChanged = true
		}
	}

	if configChanged {
		if err := saveModulesConfig(configPath, cfg); err != nil {
			fmt.Fprintf(os.Stderr, "Warning: failed to save updated %s: %v\n", configPath, err)
		} else {
			fmt.Println("[+] Synced modules in configs/modules.yaml")
		}
	}

	sort.Slice(discovered, func(i, j int) bool {
		return discovered[i].Name < discovered[j].Name
	})

	// 4. Print Status Report Table
	printStatusTable(discovered)

	// 4.5 Validate Module Dependencies & Conflicts
	validationErrors := validateDependencies(discovered)
	if len(validationErrors) > 0 {
		fmt.Println("================================================================================")
		fmt.Println(" [!] MODULE DEPENDENCY VALIDATION FAILED")
		fmt.Println("================================================================================")
		fmt.Println(" The following module dependency conflicts / missing parent modules were detected:")
		for _, e := range validationErrors {
			fmt.Printf("   ❌ %s\n", e)
		}
		fmt.Println("\n How to resolve:")
		fmt.Println("   1. Enable the required parent module(s) in configs/modules.yaml, OR")
		fmt.Println("   2. Disable the dependent child module(s) in configs/modules.yaml.")
		fmt.Println("================================================================================")
		os.Exit(1)
	}

	// 5. Filter active modules & binds
	var activeMods, migratorMods, routeMods, backgroundMods []*ModuleInfo
	var activeBinds []WireBind

	for _, mod := range discovered {
		if mod.Enabled {
			activeMods = append(activeMods, mod)
			if mod.HasAutoMigrate {
				migratorMods = append(migratorMods, mod)
			}
			if mod.HasRoutes {
				routeMods = append(routeMods, mod)
			}
			if mod.HasBackground {
				backgroundMods = append(backgroundMods, mod)
			}

			for _, b := range mod.Binds {
				// Only include bind if the source module is also enabled (or if no specific module prefix)
				if b.SourceModule == "" || enabledMap[b.SourceModule] {
					activeBinds = append(activeBinds, b)
				}
			}
		}
	}

	// 6. Generate cmd/api/modules_gen.go
	tmpl, err := template.New("modules_gen").Parse(modulesGenTemplate)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Template parse error: %v\n", err)
		os.Exit(1)
	}

	var buf bytes.Buffer
	err = tmpl.Execute(&buf, map[string]any{
		"ActiveModules":     activeMods,
		"ActiveBinds":       activeBinds,
		"MigratorModules":   migratorMods,
		"RouteModules":      routeMods,
		"BackgroundModules": backgroundMods,
		"HasAuthModule":     enabledMap["auth"],
	})
	if err != nil {
		fmt.Fprintf(os.Stderr, "Template execute error: %v\n", err)
		os.Exit(1)
	}

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		fmt.Fprintf(os.Stderr, "Go format error: %v\nRaw output:\n%s\n", err, buf.String())
		os.Exit(1)
	}

	if err := os.WriteFile(genFile, formatted, 0644); err != nil {
		fmt.Fprintf(os.Stderr, "Failed to write %s: %v\n", genFile, err)
		os.Exit(1)
	}

	fmt.Printf("[✓] Generated %s\n", filepath.Join("cmd", "api", "modules_gen.go"))

	// 7. Run wire command
	fmt.Println("[*] Running Wire dependency injection generator...")
	wireBin := findWireBinary()
	var cmdWire *exec.Cmd
	if wireBin != "" {
		cmdWire = exec.Command(wireBin)
	} else {
		cmdWire = exec.Command("go", "run", "github.com/google/wire/cmd/wire")
	}
	cmdWire.Dir = filepath.Join(rootDir, "cmd", "api")
	cmdWire.Stdout = os.Stdout
	cmdWire.Stderr = os.Stderr
	if err := cmdWire.Run(); err != nil {
		fmt.Fprintf(os.Stderr, "[!] Wire failed: %v. Please make sure wire CLI is installed ('make install-tools').\n", err)
		os.Exit(1)
	}
	fmt.Println("[✓] Wire generation completed successfully (cmd/api/wire_gen.go)")
	fmt.Println("================================================================================")
	fmt.Println(" Setup finished! Run 'make run' or 'make test' to proceed.")
	fmt.Println("================================================================================")
}

func findWireBinary() string {
	if path, err := exec.LookPath("wire"); err == nil {
		return path
	}
	if gopath := os.Getenv("GOPATH"); gopath != "" {
		p := filepath.Join(gopath, "bin", "wire")
		if _, err := os.Stat(p); err == nil {
			return p
		}
	}
	if home, err := os.UserHomeDir(); err == nil {
		p := filepath.Join(home, "go", "bin", "wire")
		if _, err := os.Stat(p); err == nil {
			return p
		}
	}
	return ""
}

func findProjectRoot() (string, error) {
	dir, err := os.Getwd()
	if err != nil {
		return "", err
	}

	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir, nil
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			break
		}
		dir = parent
	}
	return "", fmt.Errorf("go.mod not found in parent directories")
}

func loadModulesConfig(path string) (*ModulesConfig, error) {
	cfg := &ModulesConfig{Modules: make(map[string]ModuleEntry)}
	data, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			return cfg, nil
		}
		return nil, err
	}
	if err := yaml.Unmarshal(data, cfg); err != nil {
		return nil, err
	}
	if cfg.Modules == nil {
		cfg.Modules = make(map[string]ModuleEntry)
	}
	return cfg, nil
}

func saveModulesConfig(path string, cfg *ModulesConfig) error {
	data, err := yaml.Marshal(cfg)
	if err != nil {
		return err
	}
	header := []byte("# ==============================================================================\n" +
		"# MODULE REGISTRY & ACTIVATION CONFIGURATION\n" +
		"# ==============================================================================\n" +
		"# Run 'make setup' to sync this file, regenerate DI wiring, and compile.\n" +
		"# Set 'enabled: false' to disable a module without deleting its code.\n" +
		"# ==============================================================================\n\n")
	return os.WriteFile(path, append(header, data...), 0644)
}

func scanModules(modulesDir string) ([]*ModuleInfo, error) {
	entries, err := os.ReadDir(modulesDir)
	if err != nil {
		return nil, err
	}

	var result []*ModuleInfo
	fset := token.NewFileSet()

	for _, entry := range entries {
		if !entry.IsDir() {
			continue
		}

		modName := entry.Name()
		registerFile := filepath.Join(modulesDir, modName, "register.go")

		if _, err := os.Stat(registerFile); os.IsNotExist(err) {
			continue
		}

		node, err := parser.ParseFile(fset, registerFile, nil, 0)
		if err != nil {
			return nil, fmt.Errorf("failed to parse %s: %w", registerFile, err)
		}

		info := &ModuleInfo{
			Name:        modName,
			ImportPath:  fmt.Sprintf("codebasego/internal/modules/%s", modName),
			PackageName: node.Name.Name,
		}

		// Parse annotations from comments
		fileData, err := os.ReadFile(registerFile)
		if err == nil {
			scanner := bufio.NewScanner(bytes.NewReader(fileData))
			for scanner.Scan() {
				line := scanner.Text()
				matches := bindRegex.FindStringSubmatch(line)
				if len(matches) == 3 {
					rawTarget := matches[1]
					rawSource := matches[2]

					target := rawTarget
					if !strings.Contains(target, ".") {
						target = fmt.Sprintf("%s.%s", info.PackageName, target)
					}

					// Extract source module name if available
					cleanSource := strings.TrimPrefix(rawSource, "*")
					sourceMod := ""
					if parts := strings.Split(cleanSource, "."); len(parts) > 1 {
						sourceMod = parts[0]
					}

					info.Binds = append(info.Binds, WireBind{
						Target:       target,
						Source:       rawSource,
						SourceModule: sourceMod,
					})
				}
			}
		}

		// Inspect AST
		ast.Inspect(node, func(n ast.Node) bool {
			switch x := n.(type) {
			case *ast.ValueSpec:
				for _, name := range x.Names {
					if name.Name == "ProviderSet" {
						info.HasProviderSet = true
					}
				}
			case *ast.FuncDecl:
				if x.Recv != nil && len(x.Recv.List) > 0 {
					methodName := x.Name.Name
					switch methodName {
					case "AutoMigrate":
						info.HasAutoMigrate = true
					case "RegisterRoutes":
						info.HasRoutes = true
					case "StartBackground":
						info.HasBackground = true
					}
				}
			}
			return true
		})

		result = append(result, info)
	}

	return result, nil
}

func printStatusTable(modules []*ModuleInfo) {
	fmt.Println("================================================================================")
	fmt.Println("               CODEBASE MODULE REGISTRY & DI AUTOMATION                         ")
	fmt.Println("================================================================================")
	fmt.Printf("%-12s | %-10s | %-9s | %-7s | %-10s | %s\n", "MODULE", "STATUS", "MIGRATE", "ROUTES", "BACKGROUND", "DESCRIPTION")
	fmt.Println("--------------------------------------------------------------------------------")

	activeCount := 0
	inactiveCount := 0

	for _, m := range modules {
		statusStr := "[ENABLED]"
		if !m.Enabled {
			statusStr = "[DISABLED]"
			inactiveCount++
		} else {
			activeCount++
		}

		migrateStr := "No"
		if m.HasAutoMigrate {
			migrateStr = "Yes"
		}

		routesStr := "No"
		if m.HasRoutes {
			routesStr = "Yes"
		}

		bgStr := "No"
		if m.HasBackground {
			bgStr = "Yes"
		}

		fmt.Printf("%-12s | %-10s | %-9s | %-7s | %-10s | %s\n",
			m.Name, statusStr, migrateStr, routesStr, bgStr, m.Description)
	}
	fmt.Println("--------------------------------------------------------------------------------")
	fmt.Printf("Summary: %d Active | %d Inactive | %d Total Modules\n\n",
		activeCount, inactiveCount, len(modules))
}

func validateDependencies(discovered []*ModuleInfo) []string {
	var errs []string
	modMap := make(map[string]*ModuleInfo)
	for _, m := range discovered {
		modMap[m.Name] = m
	}

	for _, mod := range discovered {
		if !mod.Enabled {
			continue
		}

		for _, bind := range mod.Binds {
			if bind.SourceModule == "" {
				continue
			}

			// Check if source module exists
			srcMod, exists := modMap[bind.SourceModule]
			if !exists {
				errs = append(errs, fmt.Sprintf("Module '%s' is ENABLED but requires module '%s' (binding %s -> %s), which does not exist.",
					mod.Name, bind.SourceModule, bind.Target, bind.Source))
				continue
			}

			// Check if source module is enabled
			if !srcMod.Enabled {
				errs = append(errs, fmt.Sprintf("Module '%s' is ENABLED but requires parent module '%s' (binding %s -> %s), which is DISABLED in configs/modules.yaml.",
					mod.Name, bind.SourceModule, bind.Target, bind.Source))
			}
		}
	}

	// Check circular dependencies
	for _, modA := range discovered {
		if !modA.Enabled {
			continue
		}
		for _, bindA := range modA.Binds {
			if bindA.SourceModule == "" || bindA.SourceModule == modA.Name {
				continue
			}
			if modB, ok := modMap[bindA.SourceModule]; ok && modB.Enabled {
				for _, bindB := range modB.Binds {
					if bindB.SourceModule == modA.Name {
						errs = append(errs, fmt.Sprintf("Circular dependency conflict detected between module '%s' and module '%s'.",
							modA.Name, modB.Name))
					}
				}
			}
		}
	}

	return errs
}

